export const menuItemLabels = {
    AUDIT: 'Журнал аудита',
    CATEGORY: 'Категории',
    DZO: 'ДЗО',
    REFERENCE_BOOKS: 'Справочники',
    REPORTS: 'Отчёты',
    USERS: 'Пользователи',
    PROMO_CAMPAIGNS: 'Промо-кампании',
    DASHBOARD: 'Дашборд',
    PRESENTATION: 'Презентация',
    INSTRUCTIONS: 'Инструкции',
    SETTINGS: 'Настройки',
    APP: 'Приложения',
    GROUPS: 'Группы',
    CONSENTS: 'Согласие',
    SALE_POINT: 'Точка продажи',
    LOCATION: 'Локация',
    SALE_POINT_TYPE: 'Тип точки продаж',
    LOCATION_TYPE: 'Тип локации',
    BUSINESS_ROLE: 'Бизнес-роль',
    ROLE_IN_CANAL: 'Роль в канале',
    DEVICE_TYPE: 'Тип устройства',
    CANAL_TYPE: 'Тип канала',
};
