export const menuItemLabels = {
    AUDIT: 'Журнал аудита',
    CATEGORY: 'Категории',
    DZO: 'ДЗО',
    REPORTS: 'Отчёты',
    USERS: 'Пользователи',
    PROMO_CAMPAIGNS: 'Промо-кампании',
    DASHBOARD: 'Дашборд',
    PRESENTATION: 'Презентация',
    INSTRUCTIONS: 'Инструкции',
    SETTINGS: 'Настройки',
    APP: 'Приложения',
    GROUPS: 'Группы',
    CONSENTS: 'Согласие',
};
